                             -- SEND EMAIL FROM DATABASE TO USER --
CREATE TABLE CUSTOMERS1
(
  ID INT IDENTITY(1001,1),
  NAME VARCHAR(70),
  AGE INT,
  MOBILENUM CHAR(10),
  EMAIL VARCHAR(100) NOT NULL,
  REGISTER_DATE DATE DEFAULT GETDATE(),
  EXPIRED_DATE DATE DEFAULT DATEADD(MONTH,1,GETDATE())
  )

  INSERT INTO CUSTOMERS1(NAME,AGE,MOBILENUM,EMAIL) VALUES ('KALAI',23,9876543210,'kalaivanan7787@gmail.com')
  INSERT INTO CUSTOMERS1(NAME,AGE,MOBILENUM,EMAIL) VALUES ('NANDHA',23,9876543210,'nandha@gmail.com')
  INSERT INTO CUSTOMERS1(NAME,AGE,MOBILENUM,EMAIL) VALUES ('NIZAR',23,9876543210,'nizar@gmail.com')
  INSERT INTO CUSTOMERS1(NAME,AGE,MOBILENUM,EMAIL) VALUES ('SAI',23,9876543210,'sai7787@gmail.com')

  SELECT * FROM CUSTOMERS1

  UPDATE CUSTOMERS1 SET EXPIRED_DATE = '2024-09-12' WHERE ID = 1001

  ---------------------------------------------------------------------------------------------------------

SELECT ID,NAME,EMAIL, 
CASE 
     WHEN EXPIRED_DATE < GETDATE() 
	 THEN 'EXPIRED'
     ELSE 'NOT EXPIRED'
END AS EXPIRYSTATUS
FROM CUSTOMERS1 WHERE EXPIRED_DATE < GETDATE()

  ---------------------------------------------------------------------------------------------------------
  
DECLARE @ID INT
DECLARE @NAME VARCHAR(70)
DECLARE @AGE INT
DECLARE @MOBILENUM CHAR(10)
DECLARE @EMAIL VARCHAR(100)
DECLARE @REGISTER_DATE DATE 
DECLARE @EXPIRED_DATE DATE
DECLARE @SUBJECT VARCHAR(50)
DECLARE @MESSAGE VARCHAR(200)

DECLARE CURSORNAME CURSOR FOR
SELECT ID, NAME, EMAIL from CUSTOMERS1 WHERE EXPIRED_DATE < GETDATE()

OPEN CURSORNAME
FETCH NEXT FROM CURSORNAME INTO @ID,@NAME,@EMAIL

WHILE @@FETCH_STATUS = 0
BEGIN
	SET @SUBJECT = 'Subscription Expiried'
	SET @MESSAGE = 'Hello ' + @NAME + ', Your subscription has been expired. Please renew to continue the services'

	EXEC MSDB.DBO.sp_send_dbmail 
	@PROFILE_NAME = 'Test Mail',
	@RECIPIENTS = @EMAIL,
	@SUBJECT = @SUBJECT,
	@BODY = @MESSAGE
	FETCH NEXT FROM CURSORNAME INTO @ID,@NAME,@EMAIL
END

CLOSE CURSORNAME
DEALLOCATE CURSORNAME

  ---------------------------------------------------------------------------------------------------------



