CREATE DATABASE DEMODATABASE

USE DEMODATABASE

CREATE TABLE SALESDATA 
(
    ID INT PRIMARY KEY,
    VALUE INT,
    TOTAL INT
)

INSERT INTO SALESDATA (ID, Value)
VALUES (1, 10), (2, 20), (3, 15), (4, 25), (5, 30)

SELECT * FROM SALESDATA

  ---------------------------------------------------------------------------------------------------------

DECLARE @ID INT
DECLARE @VALUE INT
DECLARE @TOTAL INT = 0

DECLARE TOTALCURSORNAME CURSOR FOR
SELECT ID, VALUE FROM SALESDATA
ORDER BY ID

OPEN TOTALCURSORNAME
FETCH NEXT FROM TOTALCURSORNAME INTO @ID, @VALUE

WHILE @@FETCH_STATUS = 0
BEGIN
	SET @TOTAL = @TOTAL + @VALUE
	UPDATE SALESDATA set TOTAL = @TOTAL where Id = @Id
	FETCH NEXT FROM TOTALCURSORNAME INTO @Id, @VALUE
END
CLOSE TOTALCURSORNAME
DEALLOCATE TOTALCURSORNAME

SELECT * FROM SALESDATA

  ---------------------------------------------------------------------------------------------------------
