-- TRIGGERS --
CREATE TABLE RESULTTABLE
(
EMPLOYEE_ID INT,
PROCESS VARCHAR(20),
UPDATED_DATE DATE
)

-- VIRUTUAL TABLE FOR DATAS --

CREATE TRIGGER TRIGGER_NAME ON EMPLOYEES
AFTER INSERT
AS BEGIN
INSERT INTO RESULTTABLE
SELECT EMPLOYEE_ID,'INSERT',GETDATE() FROM INSERTED
END

-- TRIGGER CREATION FOR INSERT --

INSERT INTO employees VALUES (207,'KANE William','Gietz',8300,205,110)

DELETE FROM employees WHERE employee_id = 207

CREATE TRIGGER TRIGGER_NAME_1 ON EMPLOYEES
AFTER DELETE
AS BEGIN
INSERT INTO RESULTTABLE
SELECT EMPLOYEE_ID,'DELETE',GETDATE() FROM DELETED
END

-- TRIGGER CREATION FOR DELETE --

ALTER TRIGGER TRIGGER_NAME ON EMPLOYEES
AFTER INSERT , DELETE
AS BEGIN
INSERT INTO RESULTTABLE
SELECT EMPLOYEE_ID,'INSERT',GETDATE() FROM INSERTED

UNION ALL

SELECT EMPLOYEE_ID,'DELETE',GETDATE() FROM DELETED
END

-- ALTER TRIGGER FOR BOTH INSERT & DELETE --

-- TRIGGER FOR CURRENT PURPOSE COUNT [INSERT/UPDATE/DELETE] --

CREATE TRIGGER TRIGGER_NAME_2 ON EMPLOYEES 
FOR INSERT
AS BEGIN
SELECT COUNT(*) FROM EMPLOYEES
END